//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomiPlus.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamento
    {
        public int nIdDepartamento { get; set; }
        public string sDepartamento { get; set; }
        public string sNombreEncargado { get; set; }
        public int nIdSucursal { get; set; }
        public string sTelefono { get; set; }
        public string sFax { get; set; }
        public string sEmail { get; set; }
        public bool bActivo { get; set; }
    }
}
