//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomiPlus.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        public int nIdDireccion { get; set; }
        public string sCalle { get; set; }
        public string sNoInterno { get; set; }
        public string sNoExterno { get; set; }
        public Nullable<int> nIdColonia { get; set; }
    }
}
