//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomiPlus.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int nIdEmpleado { get; set; }
        public string sNombre { get; set; }
        public string sPrimerApellido { get; set; }
        public string sSegundoApellido { get; set; }
        public int nIdDepartamento { get; set; }
        public int nIdPeriodicidad { get; set; }
        public string sRFC { get; set; }
        public string sCURP { get; set; }
        public string nNSS { get; set; }
        public string nNoInfonavit { get; set; }
        public System.DateTime sFecharegistro { get; set; }
        public string sSexo { get; set; }
        public int nIdTipoTrabajador { get; set; }
        public int nIdTipoSalario { get; set; }
        public int nIdEstadoNacimiento { get; set; }
        public string sUMF { get; set; }
        public Nullable<System.DateTime> dFechaAltaIMSS { get; set; }
        public int nIdDireccion { get; set; }
        public decimal nSalarioDiario { get; set; }
        public decimal nSDI { get; set; }
        public Nullable<System.DateTime> dFechaBaja { get; set; }
        public int nIdCausaBaja { get; set; }
        public Nullable<System.DateTime> dFechaReingreso { get; set; }
        public int nIdOcupacion { get; set; }
        public int nIdSucursal { get; set; }
        public bool bActivo { get; set; }
    }
}
