//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomiPlus.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public Empresa()
        {
            this.Sucursal = new HashSet<Sucursal>();
            this.UsuarioEmpresa = new HashSet<UsuarioEmpresa>();
        }
    
        public int nIdEmpresa { get; set; }
        public string sRazonSocial { get; set; }
        public string sRFC { get; set; }
        public string sCURP { get; set; }
        public string sRegimenFiscal { get; set; }
        public int nIdDireccion { get; set; }
        public string sRepresentanteLegal { get; set; }
        public string sEmailContacto { get; set; }
        public string sTelefono { get; set; }
        public string sFAx { get; set; }
        public string sPaginaWeb { get; set; }
        public Nullable<System.DateTime> sFechaRegistro { get; set; }
        public string sLogo { get; set; }
        public Nullable<bool> bActivo { get; set; }
    
        public virtual Direccion Direccion { get; set; }
        public virtual ICollection<Sucursal> Sucursal { get; set; }
        public virtual ICollection<UsuarioEmpresa> UsuarioEmpresa { get; set; }
    }
}
