//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomiPlus.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estado
    {
        public Estado()
        {
            this.Ciudad = new HashSet<Ciudad>();
            this.Empleado = new HashSet<Empleado>();
        }
    
        public int nIdEstado { get; set; }
        public string sEstado { get; set; }
        public int nIdPais { get; set; }
    
        public virtual ICollection<Ciudad> Ciudad { get; set; }
        public virtual ICollection<Empleado> Empleado { get; set; }
        public virtual Pais Pais { get; set; }
    }
}
