//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomiPlus.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A06759_NOMINASEntities : DbContext
    {
        public DB_A06759_NOMINASEntities()
            : base("name=DB_A06759_NOMINASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CausaBaja> CausaBaja { get; set; }
        public DbSet<Ciudad> Ciudad { get; set; }
        public DbSet<Colonia> Colonia { get; set; }
        public DbSet<Departamento> Departamento { get; set; }
        public DbSet<Direccion> Direccion { get; set; }
        public DbSet<Empleado> Empleado { get; set; }
        public DbSet<Empresa> Empresa { get; set; }
        public DbSet<Estado> Estado { get; set; }
        public DbSet<Municipio> Municipio { get; set; }
        public DbSet<Ocupaciones> Ocupaciones { get; set; }
        public DbSet<Pais> Pais { get; set; }
        public DbSet<Periodicidad> Periodicidad { get; set; }
        public DbSet<Rol> Rol { get; set; }
        public DbSet<Sucursal> Sucursal { get; set; }
        public DbSet<TipoSalario> TipoSalario { get; set; }
        public DbSet<TipoTrabajador> TipoTrabajador { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<UsuarioEmpresa> UsuarioEmpresa { get; set; }
    }
}
