//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomiPlus.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomina
    {
        public Nomina()
        {
            this.Nomina1 = new HashSet<Nomina>();
        }
    
        public int nIdNomina { get; set; }
        public int nIdEmpresa { get; set; }
        public string sNombre { get; set; }
        public System.DateTime dFechaRegistro { get; set; }
        public System.DateTime dFechaFin { get; set; }
        public System.DateTime dFechaInicio { get; set; }
        public int nEsquemaPago { get; set; }
        public string sEstatus { get; set; }
    
        public virtual ICollection<Nomina> Nomina1 { get; set; }
        public virtual Nomina Nomina2 { get; set; }
    }
}
