//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomiPlus.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pais
    {
        public Pais()
        {
            this.Estado = new HashSet<Estado>();
        }
    
        public int nIdPais { get; set; }
        public string sPais { get; set; }
    
        public virtual ICollection<Estado> Estado { get; set; }
    }
}
