//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomiPlus.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        public Sucursal()
        {
            this.Departamento = new HashSet<Departamento>();
            this.Empleado = new HashSet<Empleado>();
        }
    
        public int nIdSucursal { get; set; }
        public string sNombreSucursal { get; set; }
        public int nIdDireccion { get; set; }
        public int nIdEmpresa { get; set; }
        public System.DateTime sFechaRegistro { get; set; }
        public string sTelefono { get; set; }
        public string sFax { get; set; }
        public string sEmail { get; set; }
        public string sNombreEncargado { get; set; }
        public Nullable<bool> bActivo { get; set; }
    
        public virtual ICollection<Departamento> Departamento { get; set; }
        public virtual Direccion Direccion { get; set; }
        public virtual ICollection<Empleado> Empleado { get; set; }
        public virtual Empresa Empresa { get; set; }
    }
}
