//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NomiPlus.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.UsuarioEmpresa = new HashSet<UsuarioEmpresa>();
        }
    
        public int nIdUsuario { get; set; }
        public string sNombre { get; set; }
        public string sPrimerApellido { get; set; }
        public string sSegundoApellido { get; set; }
        public int nIdRol { get; set; }
        public string sUsuario { get; set; }
        public string sContraseña { get; set; }
        public bool bActivo { get; set; }
        public string nIdEmpresa { get; set; }
    
        public virtual Rol Rol { get; set; }
        public virtual ICollection<UsuarioEmpresa> UsuarioEmpresa { get; set; }
    }
}
